version: '3.8'
services:
  namenode: ### main part of HDFS - keeps files matadata
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    platform: linux/amd64
    environment:
      - CLUSTER_NAME=nm-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_permissions_enabled=false 
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    ports:
      - "9000:9000"
      - "9870:9870"

  datanode:  ### data warehouse - keeps data in HDFS 
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    platform: linux/amd64
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_NAMENODE_URI=hdfs://namenode:9000
      - DFS_DATANODE_USE_DATANODE_HOSTNAME=true
    volumes:
      - hdfs_datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  hdfs-init: 
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-init
    platform: linux/amd64
    depends_on:
      - namenode
      - datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    entrypoint: ["/bin/bash", "-c"]
    command: |
      echo "STARTING HDFS INIT..."
      
      until hdfs dfs -ls /; do 
        echo "Waiting for NameNode..."
        sleep 5
      done

      echo "Leaving Safe Mode..."
      hdfs dfsadmin -safemode leave

      echo "Creating directories..."
      hdfs dfs -mkdir -p /user/hdfs/electricitymaps/zone_PL
      hdfs dfs -mkdir -p /user/hdfs/openmeteo/warsaw
      
      if [ $$? -eq 0 ]; then
        echo "Directories created successfully."
      else
        echo "FAILED to create directories."
        exit 1
      fi

      hdfs dfs -chmod -R 777 /user
      
      echo "Structure:"
      hdfs dfs -ls -R /
      echo "HDFS INIT FINISHED."

  nifi:  ### to create init folders and permissions
    image: apache/nifi:1.25.0
    container_name: nifi
    ports:
      - "8080:8080"
    volumes:
      - ./nifi:/opt/nifi/nifi-current/templates
      - nifi_state:/opt/nifi/nifi-current/flow
    environment:
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - NIFI_WEB_HTTP_PORT=8080
    depends_on:
      - hdfs-ingester

  hdfs-ingester:  ### python microservis in flask - NiFi sends JSON on /ingest
    build: ./hdfs_ingester
    container_name: hdfs-ingester
    environment:
      - NAMENODE_HOST=namenode
      - NAMENODE_PORT=9870
      - HDFS_USER=hdfs
      - DATANODE_HOST=datanode
      - DATANODE_PORT=9864
      - PYTHONUNBUFFERED=1
    depends_on:
      namenode:
        condition: service_started
      datanode:
        condition: service_started
      hdfs-init:
        condition: service_completed_successfully
    ports:
      - "5050:5000"

  tester:
    build: ./tests
    container_name: tester
    environment:
      - ELECTRICITYMAPS_TOKEN=${ELECTRICITYMAPS_TOKEN}
      - NAMENODE_HOST=namenode
      - NAMENODE_PORT=9870
    depends_on:
      - nifi
      - hdfs-ingester
      - namenode

volumes:
  hdfs_namenode:
  hdfs_datanode:
  nifi_state: