version: '3.8'
services:
  namenode: ### main part of HDFS - keeps files matadata
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    platform: linux/amd64
    environment:
      - CLUSTER_NAME=nm-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_permissions_enabled=false 
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    ports:
      - "9000:9000"
      - "9870:9870"

  datanode:  ### data warehouse - keeps data in HDFS 
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    platform: linux/amd64
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_NAMENODE_URI=hdfs://namenode:9000
      - DFS_DATANODE_USE_DATANODE_HOSTNAME=true
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hdfs_datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    ports:
      - "9864:9864"
      - "9866:9866"

  hdfs-init: 
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-init
    platform: linux/amd64
    depends_on:
      - namenode
      - datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    entrypoint: ["/bin/bash", "-c"]
    command: |
      echo "STARTING HDFS INIT..."
      
      until hdfs dfs -ls /; do 
        echo "Waiting for NameNode..."
        sleep 5
      done

      echo "Leaving Safe Mode..."
      hdfs dfsadmin -safemode leave

      echo "Creating directories..."
      hdfs dfs -mkdir -p /user/hdfs/electricitymaps/zone_PL
      hdfs dfs -mkdir -p /user/hdfs/openmeteo/warsaw
      
      if [ $$? -eq 0 ]; then
        echo "Directories created successfully."
      else
        echo "FAILED to create directories."
        exit 1
      fi

      hdfs dfs -chmod -R 777 /user
      
      echo "Structure:"
      hdfs dfs -ls -R /
      echo "HDFS INIT FINISHED."

  nifi:  ### to create init folders and permissions
    image: apache/nifi:1.25.0
    container_name: nifi
    ports:
      - "8080:8080"
    volumes:
      - ./nifi:/opt/nifi/nifi-current/templates
      - nifi_state:/opt/nifi/nifi-current/flow
      - nifi_conf:/opt/nifi/nifi-current/conf
    environment:
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - NIFI_WEB_HTTP_PORT=8080
    depends_on:
      - hdfs-ingester
      - kafka


  hdfs-ingester:  ### python microservis in flask - NiFi sends JSON on /ingest
    build: ./hdfs_ingester
    container_name: hdfs-ingester
    environment:
      - NAMENODE_HOST=namenode
      - NAMENODE_PORT=9870
      - HDFS_USER=hdfs
      - DATANODE_HOST=datanode
      - DATANODE_PORT=9864
      - PYTHONUNBUFFERED=1
    depends_on:
      namenode:
        condition: service_started
      datanode:
        condition: service_started
      hdfs-init:
        condition: service_completed_successfully
    ports:
      - "5050:5000"

  tester:
    build: ./tests
    container_name: tester
    environment:
      - ELECTRICITYMAPS_TOKEN=${ELECTRICITYMAPS_TOKEN}
      - NAMENODE_HOST=namenode
      - NAMENODE_PORT=9870
    depends_on:
      - nifi
      - hdfs-ingester
      - namenode

  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      # kafka will be reachable inside Docker as "kafka:9092"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  spark:
    build: ./spark
    container_name: spark
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - kafka
    ports:
      - "4040:4040"
    command: sleep infinity

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
    ports:
      - "2000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  data-dam:
    build: ./data-dam
    container_name: data-dam
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
    volumes:
      - ./data-dam:/app
      - data-dam-store:/data


volumes:
  hdfs_namenode:
  hdfs_datanode:
  nifi_state:
  nifi_conf:
  grafana-storage:
  data-dam-store:
