{
 "title": "Display",
 "time": { "from": "now-3d", "to": "now+1d" },
 "refresh": "5s",
 "panels": [
  { "title": "Live Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prediction of Solar and Wind power production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "columnId": "blobAsBigInt(bigintAsBlob(1))",
     "columnTime": "datetime",
     "columnValue": "solar_pred",
     "keyspace": "weather",
     "table": "predictions",
     "target": "SELECT cast(blobAsBigInt(bigintAsBlob(1)) as text) AS id, datetime, solar_pred AS \"Solar\", wind_pred AS \"Wind\"\nFROM weather.predictions",
     "valueId": "1"
    }
   ]
  },
  {
   "title": "Recent Temperature and Shortwave Radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "target": "SELECT cast(blobAsBigInt(bigintAsBlob(1)) as text) AS id, datetime,\ntemperature_2m as \"Temperature\", shortwave_radiation AS \"Shortwave Radiation\"\nFROM weather.cur_weather"
    }
   ]
  },
  {
   "title": "Actual Recent Electricity Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "target": "SELECT cast(blobAsBigInt(bigintAsBlob(1)) as text) AS id, datetime,\nsolar_actual AS \"Solar\", wind_actual AS \"Wind\"\nFROM weather.cur_electricity"
    }
   ]
  },
  {
   "title": "Recent Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "target": "SELECT cast(blobAsBigInt(bigintAsBlob(1)) as text) AS id, datetime, wind_speed_10m AS \"Wind Speed\"\nFROM weather.cur_weather"
    }
   ]
  },
  { "title": "Batch Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Previous Wind Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "columnId": "id",
     "columnTime": "datetime",
     "columnValue": "actual",
     "keyspace": "weather",
     "table": "solar_training",
     "target": "SELECT id, datetime, actual, predicted\nFROM weather.wind_training"
    }
   ]
  },
  {
   "title": "Previous Solar Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "columnId": "id",
     "columnTime": "datetime",
     "columnValue": "actual",
     "keyspace": "weather",
     "table": "solar_training",
     "target": "SELECT id, datetime, actual, predicted\nFROM weather.solar_training"
    }
   ]
  },
  {
   "title": "R2 of Wind training",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columnId": "model",
     "columnTime": "datetime",
     "columnValue": "r2",
     "keyspace": "weather",
     "table": "ml_metrics",
     "target": "SELECT r2\nFROM weather.ml_metrics\nWHERE model = 'wind'\nORDER BY datetime DESC\nLIMIT 1",
     "valueId": "wind"
    }
   ]
  },
  {
   "title": "RMSE of Wind training",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "columnId": "model",
     "columnTime": "datetime",
     "columnValue": "rmse",
     "keyspace": "weather",
     "table": "ml_metrics",
     "target": "SELECT rmse, model\nFROM weather.ml_metrics\nWHERE model = 'wind'\nORDER BY datetime DESC\nLIMIT 1",
     "valueId": "wind"
    }
   ]
  },
  {
   "title": "R2 of Solar training",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columnId": "model",
     "columnTime": "datetime",
     "columnValue": "r2",
     "keyspace": "weather",
     "table": "ml_metrics",
     "target": "SELECT r2\nFROM weather.ml_metrics\nWHERE model = 'solar'\nORDER BY datetime DESC\nLIMIT 1",
     "valueId": "solar"
    }
   ]
  },
  {
   "title": "RMSE of Solar training",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "columnId": "model",
     "columnTime": "datetime",
     "columnValue": "rmse",
     "keyspace": "weather",
     "table": "ml_metrics",
     "target": "SELECT rmse, model\nFROM weather.ml_metrics\nWHERE model = 'solar'\nORDER BY datetime DESC\nLIMIT 1",
     "valueId": "solar"
    }
   ]
  }
 ]
}